# Generated by Django 5.2.7 on 2025-10-17 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['data_prevista']},
        ),
        migrations.AddField(
            model_name='assunto',
            name='incidencia',
            field=models.PositiveIntegerField(default=50, help_text='De 1 a 100, representa a importância/frequência do assunto no ENEM.'),
        ),
        migrations.AlterField(
            model_name='assunto',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assuntos', to='core.materia'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_estudos', models.DateField(blank=True, null=True)),
                ('data_prova', models.DateField(blank=True, null=True)),
                ('horas_por_dia', models.PositiveIntegerField(default=2, help_text='Quantas horas (blocos de 1h) o usuário estuda por dia.')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
