# Generated by Django 5.2.7 on 2025-10-19 18:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tarefa_options_assunto_incidencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assunto',
            options={'ordering': ['materia__nome', 'nome'], 'verbose_name': 'Assunto', 'verbose_name_plural': 'Assuntos'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nome'], 'verbose_name': 'Matéria', 'verbose_name_plural': 'Matérias'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil do Usuário', 'verbose_name_plural': 'Perfis dos Usuários'},
        ),
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['data_prevista', 'prioridade'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AddField(
            model_name='assunto',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada do assunto'),
        ),
        migrations.AddField(
            model_name='assunto',
            name='dificuldade',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='medio', max_length=10),
        ),
        migrations.AddField(
            model_name='assunto',
            name='tempo_estimado',
            field=models.PositiveIntegerField(default=60, help_text='Tempo estimado em minutos para estudar este assunto'),
        ),
        migrations.AddField(
            model_name='materia',
            name='cor',
            field=models.CharField(default='#3B82F6', help_text='Cor em hexadecimal para UI', max_length=7),
        ),
        migrations.AddField(
            model_name='materia',
            name='icone',
            field=models.CharField(default='book', help_text='Nome do ícone (Lucide React)', max_length=50),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='materias_preferidas',
            field=models.ManyToManyField(blank=True, help_text='Matérias que o usuário tem mais afinidade', to='core.materia'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nivel_base',
            field=models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='objetivo',
            field=models.CharField(blank=True, help_text='Objetivo específico do usuário (ex: Medicina na USP)', max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='notas',
            field=models.TextField(blank=True, help_text='Anotações do usuário sobre a tarefa'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='prioridade',
            field=models.PositiveIntegerField(default=1, help_text='Prioridade de 1 a 5 (1 = mais importante)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tempo_gasto',
            field=models.PositiveIntegerField(default=0, help_text='Tempo gasto em minutos'),
        ),
        migrations.AlterField(
            model_name='assunto',
            name='incidencia',
            field=models.PositiveIntegerField(default=50, help_text='De 1 a 100, representa a importância/frequência do assunto no ENEM.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='horas_por_dia',
            field=models.PositiveIntegerField(default=2, help_text='Quantas horas o usuário estuda por dia.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('em_andamento', 'Em Andamento')], default='pendente', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='assunto',
            unique_together={('nome', 'materia')},
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['usuario', 'data_prevista'], name='core_tarefa_usuario_adea7d_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['usuario', 'status'], name='core_tarefa_usuario_c5c5e5_idx'),
        ),
    ]
