# Generated by Django 5.2.7 on 2025-10-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_assunto_options_alter_materia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['data_prevista'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.RemoveIndex(
            model_name='tarefa',
            name='core_tarefa_usuario_adea7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarefa',
            name='core_tarefa_usuario_c5c5e5_idx',
        ),
        migrations.RemoveField(
            model_name='assunto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='assunto',
            name='dificuldade',
        ),
        migrations.RemoveField(
            model_name='assunto',
            name='tempo_estimado',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='icone',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='materias_preferidas',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='nivel_base',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='prioridade',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='tempo_gasto',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')], default='pendente', max_length=10),
        ),
    ]
