# Generated by Django 5.2.7 on 2025-10-20 02:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tarefa_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assunto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tarefa',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='assunto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assunto',
            name='incidencia',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assunto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='data_inicio_estudos',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='data_prova',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='horas_por_dia',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='assunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='core.assunto'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Novo Cronograma', max_length=255)),
                ('dados', models.JSONField(default=dict)),
                ('data_geracao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='core.perfilusuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_geracao'],
            },
        ),
    ]
